task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 5 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/baseline2-circle/baseline2-circle/images
    ann_file: /kaggle/input/baseline2-circle/baseline2-circle/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 12
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/fisheye8k/fisheye8K/val/images
    ann_file: /kaggle/input/fisheye8k/fisheye8K/val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 12
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
